export const FETCHING_PEOPLE = 'FETCHING_PEOPLE'
export const FETCHING_PEOPLE_SUCCESS = 'FETCHING_PEOPLE_SUCCESS'
export const FETCHING_PEOPLE_FAILURE = 'FETCHING_PEOPLE_FAILURE'

export const FETCHING_CROPS = 'FETCHING_CROPS'
export const FETCHING_CROPS_SUCCESS = 'FETCHING_CROPS_SUCCESS'
export const FETCHING_CROPS_FAILURE = 'FETCHING_CROPS_FAILURE'